services:
  backend:
    image: ${DOCKERHUB_USERNAME}/soundstorm-backend:latest
    container_name: soundstorm-backend
    restart: always
    ports:
      - "8081:8081"

  frontend:
    image: ${DOCKERHUB_USERNAME}/soundstorm-frontend:latest
    container_name: soundstorm-frontend
    restart: always
    ports:
      - "80:8080"
      - "443:8080"
    depends_on:
      - backend
