version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/soundstorm-backend:latest
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
    networks:
      - soundstorm

  frontend:
      image: ${DOCKERHUB_USERNAME}/soundstorm-frontend:latest
      container_name: frontend
      restart: always
      depends_on:
        - backend
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./certbot/www:/var/www/certbot
        - ./certbot/conf:/etc/letsencrypt:ro
      ports: 
        - "80:80" 
        - "443:443"
      networks:
        - soundstorm
