version: '3.8'

services:
  backend:
    image: witcherua/soundstorm-backend:latest
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/soundstorm
    ports:
      - "5000:5000"
    networks:
      - test-soundstorm-deploy_default
    depends_on:
      - mongo

  frontend:
    image: witcherua/soundstorm-frontend:latest
    restart: always
    depends_on:
      - backend
    volumes:
      - /home/maxnrg09/test-front-deploy/html:/usr/share/nginx/html 
      - ./nginx/conf:/etc/nginx/conf.d 
      - /home/maxnrg09/certbot/www:/var/www/certbot 
      - /home/maxnrg09/certbot:/etc/letsencrypt:ro
    ports: 
      - "80:80" 
      - "443:443"
    networks:
      - test-soundstorm-deploy_default

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - test-soundstorm-deploy_default

  # --- Monitoring stack ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - test-soundstorm-deploy_default

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - test-soundstorm-deploy_default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - test-soundstorm-deploy_default

volumes:
  mongo_data:

networks:
  test-soundstorm-deploy_default:
    external: true
