version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/soundstorm-backend:latest
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/soundstorm
    ports:
      - "5000:5000"
    networks:
      - soundstorm_default
    depends_on:
      - mongo

  frontend:
    image: ${DOCKERHUB_USERNAME}/soundstorm-frontend:latest
    restart: always
    depends_on:
      - backend
    volumes:
      - /home/maxnrg09/test-front-deploy/html:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt:ro
    ports: 
      - "80:80" 
      - "443:443"
    networks:
      - soundstorm_default

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - soundstorm_default

volumes:
  mongo_data:

networks:
  soundstorm_default
    external: true
